name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-off:
    name: ${{ matrix.os }} - Go v${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - "1.22.x"
          - "1.23.x"
        os:
          - "macos-latest"
          - "windows-latest"
          - "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: |
          go test -cover --race ./...